### ISSUE TITLE
导入现有课表的时候会缺了课

### ISSUE THREAD

**Issue by viko16** [xingrz/biaozi#9]
As title，导入后少了一门必修课，

如需要可提供截图

**Comment by xingrz** [comment]
截图。。

**Comment by viko16** [comment]
![](http://miupix.cc/di/L8457W/1.jpg)

![](http://miupix.cc/di/I7UILQ/2.jpg)

**Comment by xingrz** [comment]
那就自己找到那门课打勾加回去吧。。。没办法了。

2014-06-07 17:44 GMT+08:00 viko16 notifications@github.com:

> https://camo.githubusercontent.com/63090084f5326981c802e372644c05dbf0bc02c3/687474703a2f2f6d69757069782e63632f64692f4c38343537572f312e6a7067
> 
> https://camo.githubusercontent.com/2b0759e3ca3f94b98b01ea31457f466fb84cfbd8/687474703a2f2f6d69757069782e63632f64692f493755494c512f322e6a7067
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/xingrz/biaozi/issues/9#issuecomment-45406012.

## 

陈星宇
Sing Yu Chan

**Comment by viko16** [comment]
好吧233...
